name: CI

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main, next, beta, "*.x" ]

  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@master
    # pass these inputs only if you need to custom
    # with:
    #   os: 'ubuntu-latest, macos-latest, windows-latest'
    #   version: '16, 18'
